#!/bin/bash

image_name="${IMAGE:-dev:latest}"
container_name="${image_name/:/_}_dev-env" # Replace `:` with `_` and add suffix
container_name=$(basename "$container_name") # Drop registry info from container name

xhost +local:docker 1>/dev/null

container_status=$(docker inspect -f '{{.State.Running}}' "$container_name" 2>/dev/null)
if [ -z "$container_status" ]; then

    # --net=docker-custom \

    # Run the image
    docker run \
        -i \
        -t \
        -d \
        --privileged \
        --net=host \
        -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
        -v $HOME:/$HOME \
        -e NVIDIA_DRIVER_CAPABILITIES=all \
        -e QT_X11_NO_MITSHM=1 \
        -e TZ=Pacific/Auckland \
        -e DISPLAY="$DISPLAY" \
        --gpus all \
        --name "$container_name" \
        "$image_name" \
        bash -c "tail -F /dev/null"
elif [ "$container_status" == "false" ]; then
    docker start $container_name
fi

if [ $# -eq 0 ]; then
    docker exec -e DISPLAY="$DISPLAY" -it $container_name /bin/bash
elif [ "$1" = "-it" ]; then
    shift
    docker exec -e DISPLAY="$DISPLAY" -it $container_name /bin/bash -ic "$@"
elif [ "$1" = "-i" ]; then
    shift
    docker exec -e DISPLAY="$DISPLAY" -i $container_name /bin/bash -ic "$@"
else
    docker exec -e DISPLAY="$DISPLAY" -t $container_name /bin/bash -ic "$@"
fi

