#!/usr/bin/env bash

width=${1:-90}
height=${2:-90}

# Get the last active nvim session
nvim_cwd=$(cat ~/.local/share/nvim/auto_session/session_control.json | jq -r '.current' | sed -e 's/^[^%]*//' -e 's/%2F/\//g')
nvim_basename=$(basename -s .vim $nvim_cwd)
session_name="popup-${nvim_basename}"

x_pos="C"
y_pos="C"

if (( width < 50 )); then
    x_pos="R"
fi
if (( height < 50 )); then
    y_pos="S"
fi

# Create/attach or detach the tmux session
if [ "$(tmux display-message -p -F "#{session_name}")" = "$session_name" ]; then
    tmux detach-client
else
    tmux popup -d "$nvim_cwd" -T "$session_name" -b rounded -x$x_pos -y$y_pos -w$width% -h$height% -E "tmux attach -t '$session_name' || tmux new -s '$session_name'"
fi
