require('hardtime').setup({
  disabled_keys = {
    ['<Up>']    = { 'n' },
    ['<Down>']  = { 'n' },
    ['<Left>']  = { 'n' },
    ['<Right>'] = { 'n' },
  },
  disabled_filetypes = {
    '',
    'NvimTree',
    'TelescopePrompt',
    'aerial',
    'alpha',
    'checkhealth',
    'dapui-repl',
    'dapui_breakpoints',
    'dapui_console',
    'dapui_scopes',
    'dapui_stacks',
    'dapui_watches',
    'DressingInput',
    'DressingSelect',
    'help',
    'lazy',
    'NeogitStatus',
    'NeogitLogView',
    'mason',
    'neotest-summary',
    'neo-tree',
    'neo-tree-popup',
    'netrw',
    'noice',
    'notify',
    'packer',
    'prompt',
    'qf',
    'Trouble',
    'trouble',
    'oil',
    'undotree',
    'harpoon',
  },
})

